<?xml version="1.0" encoding="utf-8"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="fwd">

  <xacro:arg name="robot_namespace" default="/" />
  <xacro:arg name="gpu" default="true"/>
  <xacro:property name="gpu" value="$(arg gpu)" />

  <!-- Wheel Properties -->
  <xacro:property name="wheel_length" value="0.1" />
  <xacro:property name="wheel_radius" value="0.15" /> 

  <!-- Wheel Mounting Positions -->
  <xacro:property name="wheelbase" value="0.4" /> <!-- distance betwee front wheel and rear wheel -->
  <xacro:property name="track" value="0.5" />  <!-- separation between left wheel and right wheel: 0.1143 + 0.4204 = 0.5347-->
  <xacro:property name="wheel_vertical_offset" value="-0.1" />

  <!-- Base Size -->
  <xacro:property name="base_x_size" value="0.6" />
  <xacro:property name="base_y_size" value="0.400" />
  <xacro:property name="base_z_size" value="0.3" />
  <xacro:property name="M_PI" value="3.14159"/>

  <!-- Included URDF/XACRO Files -->
  <xacro:include filename="$(find wbot_description)/urdf/fwd/fwd_wheel.urdf.xacro" />

  <link name="base_link">
    <inertial>
      <!-- husky 
      <mass value="46.034" />
      <origin xyz="-0.00065 -0.085 0.062" />
      <inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197" iyy="1.7386" iyz="-0.001544" izz="2.0296" /> 
      -->
      <!--  turtlebot
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" /> 
      -->
      <!-- fwd -->
      <origin  xyz="0.0083361 0.00033765 0.10648" rpy="0 0 0" />
      <mass value="13.336" />
      <inertia ixx="0.12049" ixy="5.9344E-06" ixz="-0.001006" iyy="0.32804" iyz="-7.8809E-07" izz="0.41342" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <!-- <mesh filename="package://fwd/meshes/base_linkm3.STL" /> -->
        <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>

      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
      </geometry>
    </collision>
    <!-- <collision>
      <origin xyz="0 0 ${base_z_size*3/4-0.01}" rpy="0 0 0" />
      <geometry>
        <box size="${base_x_size*4/5} ${base_y_size} ${base_z_size/2-0.02}"/>
      </geometry>
    </collision> -->
  </link>
  <gazebo reference="base_link">                   
    <material>Gazebo/Yellow</material>
  </gazebo>

  <!-- Base footprint is on the ground under the robot -->
  <link name="base_footprint"/>
  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 ${wheel_vertical_offset - wheel_radius}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="base_footprint" />
  </joint>

  <!-- Wheel links generated from macros -->
  <xacro:fwd_wheel wheel_prefix="front_left">
    <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:fwd_wheel>
  <xacro:fwd_wheel wheel_prefix="front_right">
    <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:fwd_wheel>
  <xacro:fwd_wheel wheel_prefix="rear_left">
    <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:fwd_wheel>
  <xacro:fwd_wheel wheel_prefix="rear_right">
    <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:fwd_wheel>

  <xacro:include filename="$(find wbot_description)/urdf/sensors/sensor_module.xacro"/>
  <xacro:sensor_module parent="base_link" vlp_enable="true">
      <origin xyz="0.00 0 ${base_z_size/2 + 0.3}" rpy="0 0 0" />
  </xacro:sensor_module>


  <!-- Gazebo differentiate controller -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>$(arg robot_namespace)</robotNamespace>
      <legacyModeNS>true</legacyModeNS>
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
    </plugin>
  </gazebo>

  <!-- <gazebo>
    <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>200.0</updateRate>
      <bodyName>base_link</bodyName>
      <topicName>fwd_odom_gt</topicName>
      <gaussianNoise>0.0</gaussianNoise>
      <frameName>world</frameName>
      <xyzOffsets>0 0 0</xyzOffsets>
      <rpyOffsets>0 0 0</rpyOffsets>
    </plugin>
  </gazebo> -->

</robot>
