
#---standard pioneer footprint---
#---(in meters)---
robot_radius: 0.5
footprint_padding: 0.00

transform_tolerance: 0.8
# map_type: costmap

always_send_full_costmap: true

obstacle_layer:
 enabled: true
 obstacle_range: 100 # The maximum range in meters at which to insert obstacles into the costmap using sensor data.

 raytrace_range: 100 # The maximum range in meters at which to raytrace out obstacles from the map using sensor data.

 track_unknown_space: true
 combination_method: 1

 observation_sources: point_cloud_sensor
 point_cloud_sensor: {data_type: PointCloud2, topic: /pc_topic, marking: true, clearing: true, 
 expected_update_rate: 9.0, max_obstacle_height: 0.7, min_obstacle_height: 0.4}


inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.85  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true 
  map_topic:            "/map"
