controller_frequency: 10
planner_frequency: 2       # The rate in Hz at which to run the global planning loop
recovery_behavior_enabled: false
clearing_rotation_allowed: false

TrajectoryPlannerROS:
   max_vel_x: 3
   min_vel_x: 0.01
   max_vel_y: 0.0  # zero for a differential drive robot
   min_vel_y: 0.0
   # max_vel_theta: 1.0
   # min_vel_theta: -1.0
   min_in_place_vel_theta: 0.5
   escape_vel: -0.1
   acc_lim_x: 6
   acc_lim_y: 0.0 # zero for a differential drive robot
   acc_lim_theta: 10

   holonomic_robot: false
   yaw_goal_tolerance: 0.1 # about 6 degrees
   xy_goal_tolerance: 0.1  # 10 cm
   latch_xy_goal_tolerance: false
   pdist_scale: 0.8
   gdist_scale: 0.6
   meter_scoring: true

   heading_lookahead: 0.325
   heading_scoring: false
   heading_scoring_timestep: 0.8
   occdist_scale: 0.5
   oscillation_reset_dist: 0.05
   publish_cost_grid_pc: false
   prune_plan: true

   sim_time: 3.0
   sim_granularity: 0.025
   angular_sim_granularity: 0.025
   vx_samples: 8
   vy_samples: 0 # zero for a differential drive robot
   vtheta_samples: 20
   dwa: true
   simple_attractor: false

# DWAPlannerROS:

# # Robot Configuration Parameters
#   max_vel_x: 0.5
#   min_vel_x: 0.0

#   max_vel_y: 0.0
#   min_vel_y: 0.0

#   # The velocity when robot is moving in a straight line
#   max_trans_vel:  0.55
#   min_trans_vel:  0.1
#   trans_stopped_vel: 0.1

#   max_rot_vel: 5.0
#   min_rot_vel: 0.8
#   rot_stopped_vel: 0.8

#   acc_lim_x: 1.0
#   acc_lim_theta: 2.0
#   acc_lim_y: 0.0

# # Goal Tolerance Parametes
#   yaw_goal_tolerance: 0.3
#   xy_goal_tolerance: 0.15
#   # latch_xy_goal_tolerance: false

# # Forward Simulation Parameters
#   sim_time: 4.0
#   vx_samples: 20
#   vy_samples: 0
#   vtheta_samples: 40

# # Trajectory Scoring Parameters
#   path_distance_bias: 32.0
#   goal_distance_bias: 24.0
#   occdist_scale: 0.1
#   forward_point_distance: 0.325
#   stop_time_buffer: 0.2
#   scaling_speed: 0.25
#   max_scaling_factor: 0.2

# # Oscillation Prevention Parameters
#   oscillation_reset_dist: 0.05

# # Debugging
#   publish_traj_pc : true
#   publish_cost_grid_pc: true
#   global_frame_id: world